Bug 1853138 - Switch to Email::Address::XS
bugzilla/harmony pull request #103
Opened 2024-01-12 15:35 UTC by mrenvoize

This patch updates us from using Email::Address to Email::Address::XS to resolve CVE-2015-7686.

Regex comparisons have been replaced by parse + is_valid calls as per current documentation.

#### Additional info
* [bmo#1853138](https://bugzilla.mozilla.org/show_bug.cgi?id=1853138)

2024-01-15 11:24 UTC, mrenvoize commented
To not require Email::Address::XS independently, I've cherry-picked and rebased the patches migrating from Email::Send to Email::Sender into this branch.

2024-01-15 11:31 UTC, mrenvoize commented
I'm going to need a little help getting the tests passing though.. looks like we use a separate docker build for perl dependencies that doesn't respect changes to cpanfile here.. I'll need someone to explain how your workflow works to be able to get those updated dependencies pulled in prior to the tests being able to run as expected.

2024-01-15 14:49 UTC, mrenvoize commented
Squashed a couple of minor fixes highlighted by failing tests on the corresponding 5.2 pull request.

2024-02-01 15:15 UTC, justdave requested changes
I just ran the tests and they're all failing. Looks like a missing dependency that didn't get caught. (Email::Address::Simple?)

2024-02-20 08:01 UTC, mrenvoize commented
> I just ran the tests and they're all failing. Looks like a missing dependency that didn't get caught. (Email::Address::Simple?)

I believe I resolved these as soon as they were reported, hopefully, tests should all be passing now once given the opportunity to run.  I've rebased the branch now the CircleCI updates have landed too, thanks for working on that :)

2024-02-29 15:10 UTC, mrenvoize commented
Can we run the tests here please..

2024-03-22 02:37 UTC, justdave requested changes

2024-03-22 02:37 UTC, justdave commented on Makefile.PL
> +  'Email::Sender'              => '2.600',
Given the current test failure, I think you need to mention Email::Sender::Simple here, too.

2024-03-22 07:16 UTC, justdave commented on Makefile.PL
> +  'Email::Sender'              => '2.600',
Actually, you don't.  Email::Sender::Simple can be removed from cpanfile, too.

2024-03-22 07:59 UTC, mrenvoize commented on Makefile.PL
> +  'Email::Sender'              => '2.600',
I've dropped that commit now :)

2024-03-22 08:15 UTC, justdave approved these changes

2024-03-22 08:28 UTC, merged