1879461: Runtime errors when building documentation
bugzilla/harmony pull request #105
Opened 2024-02-14 23:39 UTC by emceeaich

#### Details

This PR fixes 1879461

#### Additional info
* [bmo#](https://bugzilla.mozilla.org/show_bug.cgi?id=1879461)

#### Test Plan

1. Build documentation with ` sphinx-build -b html -d ./doctrees   en/rst ./html`
2. Confirm runtime error in bugzilla report does not occur

2024-02-15 08:49 UTC, justdave requested changes
This looks really good aside from the two issues I mentioned.  Thanks a bunch!

2024-02-15 08:49 UTC, justdave commented on docs/en/rst/conf.py
> +for line in open("../../../Bugzilla/Constants.pm"):
I like this addition. :-)  One less place to have to change the version number when we release.  Is there a reason we need '6.0' in version? Could probably make it "unknown" and then it would be obvious when programmatically discovering it fails.

2024-02-15 08:49 UTC, justdave commented on docs/en/rst/conf.py
> +
Building the API docs on RTD required changes to the `.readthedocs.yaml` file, which I don't see in this PR.  In fact, I don't see a `.readthedocs.yaml` file on this branch at all, so that file probably needs to be copied from the 5.2 branch wholesale.

2024-02-21 23:02 UTC, emceeaich commented on docs/en/rst/conf.py
> +
Fixed with 9c9fad2c93c742c62083fb41f7c7fa298f5f6121

2024-02-29 16:24 UTC, justdave approved these changes

2024-02-29 16:25 UTC, merged