Update links, and gitignore
bugzilla/harmony pull request #108
Opened 2024-03-14 23:24 UTC by emceeaich

#### Details
This PR adds/updates:
- The docs/doctree path to .gitignore since these are generated files
- Project links to point at correct bmo products/components and project links

#### Additional info
N/A

#### Questions
- What should be the value of `repository.tests` in `./contribute.json`
- What should be in `urls` in `./contribute.json`

#### Test Plan
Run `./makedocs.pl` from ./docs path in repository

2024-03-15 21:57 UTC, justdave commented
>     * What should be the value of `repository.tests` in `./contribute.json`

Probably `https://github.com/bugzilla/bugzilla/actions` or `https://github.com/bugzilla/harmony/actions`
There's also `https://app.circleci.com/pipelines/github/bugzilla/bugzilla` and `https://app.circleci.com/pipelines/github/bugzilla/harmony` ...

>     * What should be in `urls` in `./contribute.json`

Uhh, remove them? We don't really have an equivalent.

There is a contribute.json at https://www.bugzilla.org/contribute.json
We should probably merge some of the values.

2024-03-19 08:25 UTC, emceeaich commented
I've updated `repository.tests` and removed `urls`. Will review a merge with the `contribute.json` in the docs site in a separate PR.

2024-03-22 02:07 UTC, justdave requested changes

2024-03-22 02:07 UTC, justdave commented on contribute.json
> +        "tests": "https://app.circleci.com/pipelines/github/bugzilla/harmony"
Hate to do this to you now, but I just committed a change that yanked all the circleci tests in favor of doing it all in GitHub Actions some GHA can do everything we're doing in the tests.

So make this https://github.com/bugzilla/harmony/actions

2024-03-22 06:37 UTC, emceeaich commented on contribute.json
> +        "tests": "https://app.circleci.com/pipelines/github/bugzilla/harmony"
Done.

2024-03-22 07:01 UTC, justdave approved these changes

2024-03-22 07:04 UTC, merged