tidy up all files to aid merging from bmo
bugzilla/harmony pull request #71
Opened 2020-10-18 16:24 UTC by dylanwh

Some styling has drifted, so I ran perl-tidy on everything again.

2020-10-25 04:30 UTC, CyberShadow commented
I think this needs to be rebased after #64, sorry.

2020-10-31 07:12 UTC, CyberShadow requested changes

2020-10-31 07:12 UTC, CyberShadow commented on Bugzilla/UserAgent.pm
> +  qr/\(Win.*\)/           => ["IA32", "x86", "PC"],
This doesn't look right.

1. If I run perltidy 20180220, I don't get this hunk in the diff.
2. This code hasn't changed in Harmony since the last perltidy.
3. [bmo/master has the old code](https://github.com/mozilla-bteam/bmo/blob/master/Bugzilla/UserAgent.pm#L76-L86), not the new code.

I conclude something must be wrong with the way you ran perltidy. Perhaps it's the wrong version?

2021-02-13 17:27 UTC, dylanwh commented on Bugzilla/UserAgent.pm
> +  qr/\(Win.*\)/           => ["IA32", "x86", "PC"],
I did so with the most recent version, which is what we should always be using. I'll re-do this after the other changes land.

2021-02-13 17:27 UTC, closed without merging

2021-02-13 17:33 UTC, CyberShadow commented on Bugzilla/UserAgent.pm
> +  qr/\(Win.*\)/           => ["IA32", "x86", "PC"],
I suggest pinning all dependencies so that all processes are reproducible.

The 20180220 version of perltidy is specified in `Makefile.PL` and `cpanfile`, so those version numbers should presumably be bumped appropriately.

2021-03-21 05:17 UTC, justdave commented
@dylanwh do you still need this branch?