ensure SQL querys from FlagTypeComment are valid
bugzilla/harmony pull request #94
Opened 2023-06-20 10:14 UTC by userid0x0

#### Details

This PR fixes the attachment upload. Then `$types` is empty the SQL query is malformed.

#### Test Plan
1. Open the show_bug view
2. Edit the bug
3. Click _Attach New File_

2023-06-22 05:33 UTC, justdave commented
Do you have a bug filed on bugzilla.mozilla.org that goes with this?

So looking at this, it looks to me like if there are no flag types defined at all, then it's running this anyway and winding up with invalid SQL because the list is empty. So if there are no flag types, then skip this query.

2023-06-22 05:39 UTC, justdave requested changes

2023-06-22 05:39 UTC, justdave commented on extensions/FlagTypeComment/Extension.pm
>    foreach my $row (@$db_result) {
If your new "if" fails to trigger because there are no flag types, then this $db_result on line 133 is going to be undefined. I see the same problem being caused in the existing code at line 94 with the if ($id) block. (I suspect it runs anyway, but probably throws a warning about the variable being undefined in the log). The fix for this is probably to initialize $db_result as [] when it's declared at line 75.

2023-06-22 07:51 UTC, userid0x0 commented
Hi,
sorry, I did not create an issue for this. We are currently evaluating this upcoming version of bugzilla. We noticed this crash when starting with an empty database.
I force pushed the requested change.
You are correct I aligned my patch to the existing code in line 94.
Let me know if you have further requests.

2023-07-04 05:04 UTC, justdave approved these changes

2023-07-04 05:56 UTC, justdave commented
Turns out there's an existing bug for this issue from years ago that never got fixed.... [bmo#1217882](https://bugzilla.mozilla.org/show_bug.cgi?id=1217882)

2023-07-04 06:01 UTC, justdave commented
BMO wants this patch, can you make a separate pull request for this against https://github/mozilla-bteam/bmo then use the Add Attachment link to add a link to the PR to the bug (paste the PR link into the File text box, then tick the "enter manually" for the file type (it should have x-github-pullrequest filled already at that point). Edit the description to indicate it's for the BMO branch.

Thanks!

2023-07-04 06:06 UTC, merged

2023-07-04 06:07 UTC, justdave commented
Uh....  how come that didn't give me a box to edit the commit message before merging?  I wasn't intending to actually merge that yet.

2023-07-04 06:30 UTC, justdave commented
OK, branch was set up wrong for how merges were supposed to work. It's been fixed, but the old settings also prevented us from reopening this, so I guess it's landed early :/

2023-07-04 15:17 UTC, globau commented
> BMO wants this patch, can you make a separate pull request for this against https://github.com/mozilla-bteam/bmo then use the Add Attachment link to add a link to the PR to the bug (paste the PR link into the File text box, then tick the "enter manually" for the file type (it should have x-github-pullrequest filled already at that point). Edit the description to indicate it's for the BMO branch.

All you need to do is mention the bug number in the PR's commit description (eg. `Bug 1217882 - ensure SQL querys from FlagTypeComment are valid`).

Pasting the PR URL works too (note you don't need to manually set the file type; that'll happen automatically).